#!/usr/bin/env python3
"""New line detector -> steering PID -> UDP connector -> walking ONNX policy.

Run this entry point for policy walking, not run_robot.py's V2 serial output.
Only the policy process owns the STM32 serial device. No shape actions or bar
crossing commands are generated by this walking integration.
"""

from __future__ import annotations

import argparse
import math
import os
import signal
import time

from camera_config import load as load_camera
from policy_bridge import ConnectorClient, SteeringController

# TEST BRANCH (vision-test-card-stop): stop the robot the first time any card is
# detected, so the real robot can confirm cards are visible at all and from how
# far. Not a competition behaviour. Drop this branch when the test is done.
CARD_EVERY = 3      # run the card detector every Nth frame (~96 ms/frame each)


def parse_args():
    camera = load_camera()
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--camera", type=int, default=int(os.getenv("CAM_IDX", camera["index"])))
    parser.add_argument("--width", type=int, default=camera["width"])
    parser.add_argument("--height", type=int, default=camera["height"])
    parser.add_argument("--camera-height-cm", type=float,
                        default=float(os.getenv("CAM_HEIGHT_CM", camera["mount_height_cm"])))
    parser.add_argument("--camera-pitch-deg", type=float,
                        default=float(os.getenv("CAM_PITCH_DEG", camera["pitch_deg"])))
    parser.add_argument("--camera-vfov-deg", type=float,
                        default=float(os.getenv("CAM_VFOV_DEG", camera["vfov_deg"])))
    parser.add_argument("--connector-host", default="127.0.0.1")
    parser.add_argument("--connector-port", type=int, default=5006)
    parser.add_argument("--vx", type=float, default=0.4,
                        help="Forward speed with valid detection, m/s")
    parser.add_argument("--max-wz", type=float, default=0.5,
                        help="Yaw-rate limit, rad/s (0..0.5)")
    parser.add_argument("--steer-full-scale-cm", type=float, default=10.0,
                        help="Cross-track error (cm) producing max-wz; smaller means stronger steering")
    parser.add_argument("--yaw-sign", type=int, choices=(-1, 1), default=-1)
    parser.add_argument("--step-len-cm", type=float, default=float(os.getenv("STEP_LEN_CM", "8")))
    parser.add_argument("--preview-gain", type=float, default=float(os.getenv("PREVIEW_GAIN", "1")))
    parser.add_argument("--headless", action="store_true")
    parser.add_argument("--max-seconds", type=float, default=0.0,
                        help="0 runs until Ctrl+C")
    args = parser.parse_args()
    if not 1 <= args.connector_port <= 65535:
        parser.error("connector-port must be between 1 and 65535")
    if args.width <= 0 or args.height <= 0:
        parser.error("camera dimensions must be positive")
    if (not all(math.isfinite(v) for v in (args.camera_height_cm, args.camera_pitch_deg,
                                         args.camera_vfov_deg, args.max_seconds))
            or args.camera_height_cm <= 0 or not 0 < args.camera_vfov_deg < 180
            or not 0 < args.camera_pitch_deg < 90 or args.max_seconds < 0):
        parser.error("invalid camera geometry or max-seconds")
    return args


def main():
    args = parse_args()
    # Reuse the dual-mode PID defaults/environment overrides of run_robot.py.
    def gains(mode, defaults):
        return tuple(float(os.getenv(f"JETSON_PID_{mode}_{name}", str(value)))
                     for name, value in zip(("KP", "KI", "KD"), defaults))

    controller = SteeringController(
        vx=args.vx, max_wz=args.max_wz, steer_full_scale_cm=args.steer_full_scale_cm,
        yaw_sign=args.yaw_sign, step_len_cm=args.step_len_cm, preview_gain=args.preview_gain,
        straight_gains=gains("STRAIGHT", (0.83, 0.004, 0.095)),
        curve_gains=gains("CURVE", (0.83, 0.006, 0.16)),
        integral_limit=float(os.getenv("JETSON_PID_I_CLAMP", "60")),
    )
    # Lazy imports keep --help and controller tests usable without a camera stack.
    import cv2
    from line_detector_v1_warp import LineDetector
    from shape_detector import ShapeDetector
    from utils import open_camera, show_debug_windows

    stopped = False

    def stop(_signum, _frame):
        nonlocal stopped
        stopped = True

    signal.signal(signal.SIGINT, stop)
    signal.signal(signal.SIGTERM, stop)
    client = ConnectorClient(args.connector_host, args.connector_port)
    cap = None
    try:
        cap = open_camera(args.camera, args.width, args.height)
        if not cap.isOpened():
            raise RuntimeError(f"Cannot open camera {args.camera}")
        width = int(cap.get(cv2.CAP_PROP_FRAME_WIDTH)) or args.width
        height = int(cap.get(cv2.CAP_PROP_FRAME_HEIGHT)) or args.height
        detector = LineDetector(width, height, cam_height_cm=args.camera_height_cm,
                                cam_pitch_deg=args.camera_pitch_deg,
                                cam_vfov_deg=args.camera_vfov_deg)
        # Card detector: stable_frames/cooldown only gate the action output, which
        # this branch ignores - it reads dbg["card_found"], a per-frame boolean.
        cards = ShapeDetector(stable_frames=3, cooldown_ms=3200, debug=False)
        print(f"Camera {args.camera}: {width}x{height}; UDP -> "
              f"{args.connector_host}:{args.connector_port}; vx={args.vx} m/s; "
              f"max_wz={args.max_wz} rad/s; yaw_sign={args.yaw_sign}", flush=True)
        start = previous = time.monotonic()
        last_log = -math.inf
        frame_count = 0
        card_stopped = False
        fps_t0 = time.monotonic()
        fps_n = 0
        fps_val = 0.0
        det_ms = card_ms = 0.0
        while not stopped:
            now = time.monotonic()
            if args.max_seconds > 0 and now - start >= args.max_seconds:
                break
            ok, frame = cap.read()
            if not ok:
                controller.reset()
                client.publish(0.0, 0.0)
                if now - last_log >= 0.5:
                    print("[vision -> connector] camera read failed; vx=0 wz=0", flush=True)
                    last_log = now
                time.sleep(0.02)
                continue
            t_det = time.monotonic()
            _, _, confidence, visualization, debug = detector.process(frame)
            det_ms = (time.monotonic() - t_det) * 1000.0
            processed = time.monotonic()

            # Test: latch a stop the first time a card is seen, anywhere in frame
            # and at any distance. Only every Nth frame - see CARD_EVERY.
            frame_count += 1
            if not card_stopped and frame_count % CARD_EVERY == 0:
                t_card = time.monotonic()
                _, card_debug = cards.update(frame, lane_offset_cm=debug.get("fused_err"))
                card_ms = (time.monotonic() - t_card) * 1000.0
                if card_debug.get("card_found"):
                    card_stopped = True
                    print(f"[card] >>> card detected (shape={card_debug.get('shape')}); "
                          f"stopping for good", flush=True)

            if card_stopped:
                # Both must be zero: policy_runner picks the step distance with
                # np.all(command == 0), so a non-zero wz keeps it stepping in place.
                vx, wz = 0.0, 0.0
            else:
                vx, wz = controller.command(debug, confidence, processed - previous)
            previous = processed

            # Loop rate: the downstream watchdogs zero the command if vision goes
            # quiet for 0.25 s, so this number matters - keep it well above 4 Hz.
            fps_n += 1
            if processed - fps_t0 >= 1.0:
                fps_val = fps_n / (processed - fps_t0)
                fps_n, fps_t0 = 0, processed

            client.publish(vx, wz)
            if processed - last_log >= 0.5:
                print(f"[vision -> connector] fps={fps_val:4.1f} "
                      f"det={det_ms:5.1f}ms card={card_ms:5.1f}ms "
                      f"vx={vx:+.3f} m/s wz={wz:+.3f} rad/s "
                      f"steer={controller.last_steer:+.2f}cm conf={confidence:.3f} "
                      f"lost={debug.get('lost_frames', '?')}"
                      f"{'  CARD STOP' if card_stopped else ''}", flush=True)
                last_log = processed
            if not args.headless:
                label = ("CARD STOP" if card_stopped else
                         f"fps={fps_val:.1f} det={det_ms:.0f}ms vx={vx:+.2f} wz={wz:+.3f}")
                cv2.putText(frame, f"{label} Q=quit", (10, 25),
                            cv2.FONT_HERSHEY_SIMPLEX, 0.6,
                            (0, 0, 255) if card_stopped else (0, 255, 0), 2)
                cv2.imshow("Policy vision", frame)
                show_debug_windows(debug, visualization)
                if cv2.waitKey(1) & 0xFF == ord("q"):
                    break
    finally:
        client.close()
        if cap is not None:
            cap.release()
        if not args.headless:
            cv2.destroyAllWindows()
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
