#!/usr/bin/env python3
"""New line detector -> steering PID -> UDP -> walking ONNX policy.

Run this entry point for policy walking, not run_robot.py's V2 serial output.
By default it sends the historical velocity-command JSON directly to the policy
receiver on port 5005. Only the policy process owns the STM32 serial device. No
shape actions or bar-crossing commands are generated by this integration.
"""

from __future__ import annotations

import argparse
import math
import os
import signal
import time

from camera_config import load as load_camera
from policy_bridge import ConnectorClient, SteeringController


def parse_args():
    camera = load_camera()
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--camera", type=int, default=int(os.getenv("CAM_IDX", camera["index"])))
    parser.add_argument("--width", type=int, default=camera["width"])
    parser.add_argument("--height", type=int, default=camera["height"])
    parser.add_argument("--camera-height-cm", type=float,
                        default=float(os.getenv("CAM_HEIGHT_CM", camera["mount_height_cm"])))
    parser.add_argument("--camera-pitch-deg", type=float,
                        default=float(os.getenv("CAM_PITCH_DEG", camera["pitch_deg"])))
    parser.add_argument("--camera-vfov-deg", type=float,
                        default=float(os.getenv("CAM_VFOV_DEG", camera["vfov_deg"])))
    parser.add_argument("--command-host", "--connector-host", dest="command_host",
                        default="127.0.0.1",
                        help="UDP command destination host (default: policy receiver)")
    parser.add_argument("--command-port", "--connector-port", dest="command_port",
                        type=int, default=5005,
                        help="UDP command destination port; use 5006 only with connector.py")
    parser.add_argument("--vx", type=float, default=0.4,
                        help="Forward speed with valid detection, m/s")
    parser.add_argument("--max-wz", type=float, default=0.5,
                        help="Yaw-rate limit, rad/s (0..0.5)")
    parser.add_argument("--steer-full-scale-cm", type=float, default=50.0,
                        help="PID steering error producing max-wz; smaller means stronger steering")
    parser.add_argument("--yaw-sign", type=int, choices=(-1, 1), default=-1)
    parser.add_argument("--step-len-cm", type=float, default=float(os.getenv("STEP_LEN_CM", "8")))
    parser.add_argument("--preview-gain", type=float, default=float(os.getenv("PREVIEW_GAIN", "1")))
    parser.add_argument("--headless", action="store_true")
    parser.add_argument("--max-seconds", type=float, default=0.0,
                        help="0 runs until Ctrl+C")
    args = parser.parse_args()
    if not 1 <= args.command_port <= 65535:
        parser.error("command-port must be between 1 and 65535")
    if args.width <= 0 or args.height <= 0:
        parser.error("camera dimensions must be positive")
    if (not all(math.isfinite(v) for v in (args.camera_height_cm, args.camera_pitch_deg,
                                         args.camera_vfov_deg, args.max_seconds))
            or args.camera_height_cm <= 0 or not 0 < args.camera_vfov_deg < 180
            or not 0 < args.camera_pitch_deg < 90 or args.max_seconds < 0):
        parser.error("invalid camera geometry or max-seconds")
    return args


def main():
    args = parse_args()
    # Reuse the dual-mode PID defaults/environment overrides of run_robot.py.
    def gains(mode, defaults):
        return tuple(float(os.getenv(f"JETSON_PID_{mode}_{name}", str(value)))
                     for name, value in zip(("KP", "KI", "KD"), defaults))

    controller = SteeringController(
        vx=args.vx, max_wz=args.max_wz, steer_full_scale_cm=args.steer_full_scale_cm,
        yaw_sign=args.yaw_sign, step_len_cm=args.step_len_cm, preview_gain=args.preview_gain,
        straight_gains=gains("STRAIGHT", (0.83, 0.004, 0.095)),
        curve_gains=gains("CURVE", (0.78, 0.002, 0.16)),
        integral_limit=float(os.getenv("JETSON_PID_I_CLAMP", "60")),
    )
    # Lazy imports keep --help and controller tests usable without a camera stack.
    import cv2
    from line_detector_v1_warp import LineDetector
    from utils import open_camera, show_debug_windows

    stopped = False

    def stop(_signum, _frame):
        nonlocal stopped
        stopped = True

    signal.signal(signal.SIGINT, stop)
    signal.signal(signal.SIGTERM, stop)
    client = ConnectorClient(args.command_host, args.command_port)
    cap = None
    try:
        cap = open_camera(args.camera, args.width, args.height)
        if not cap.isOpened():
            raise RuntimeError(f"Cannot open camera {args.camera}")
        width = int(cap.get(cv2.CAP_PROP_FRAME_WIDTH)) or args.width
        height = int(cap.get(cv2.CAP_PROP_FRAME_HEIGHT)) or args.height
        detector = LineDetector(width, height, cam_height_cm=args.camera_height_cm,
                                cam_pitch_deg=args.camera_pitch_deg,
                                cam_vfov_deg=args.camera_vfov_deg)
        destination = "policy" if args.command_port == 5005 else "UDP destination"
        print(f"Camera {args.camera}: {width}x{height}; UDP -> {destination} "
              f"{args.command_host}:{args.command_port}; vx={args.vx} m/s; "
              f"max_wz={args.max_wz} rad/s; yaw_sign={args.yaw_sign}", flush=True)
        start = previous = time.monotonic()
        last_log = -math.inf
        while not stopped:
            now = time.monotonic()
            if args.max_seconds > 0 and now - start >= args.max_seconds:
                break
            ok, frame = cap.read()
            if not ok:
                controller.reset()
                client.publish(0.0, 0.0)
                if now - last_log >= 0.5:
                    print("[vision -> policy] camera read failed; vx=0 wz=0", flush=True)
                    last_log = now
                time.sleep(0.02)
                continue
            _, _, confidence, visualization, debug = detector.process(frame)
            processed = time.monotonic()
            vx, wz = controller.command(debug, confidence, processed - previous)
            previous = processed
            client.publish(vx, wz)
            if processed - last_log >= 0.5:
                print(f"[vision -> policy] vx={vx:+.3f} m/s wz={wz:+.3f} rad/s "
                      f"steer={controller.last_steer:+.2f}cm conf={confidence:.3f} "
                      f"lost={debug.get('lost_frames', '?')}", flush=True)
                last_log = processed
            if not args.headless:
                cv2.putText(frame, f"vx={vx:+.3f} wz={wz:+.3f} Q=quit", (10, 25),
                            cv2.FONT_HERSHEY_SIMPLEX, 0.6, (0, 255, 0), 2)
                cv2.imshow("Policy vision", frame)
                show_debug_windows(debug, visualization)
                if cv2.waitKey(1) & 0xFF == ord("q"):
                    break
    finally:
        client.close()
        if cap is not None:
            cap.release()
        if not args.headless:
            cv2.destroyAllWindows()
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
